#!/usr/bin/env bash
#stops 4-to_infinity_and_beyond process
pid=$(pgrep 4-to_infinity_and_beyond)if [ -n "$pid" ]; then
    echo "Stopping 4-to_infinity_and_beyond process with PID $pid..."
    
    pkill -P $pid
    
    echo "Process stopped successfully."
else
    echo "4-to_infinity_and_beyond process is not running."
fi
